# крайне внимательно к созданию схемы и таблиц средствами jpa-hibernate!

# к созданию схемы причастны
# javax.persistence.schema-generation.database.action
# и jpa.properties.hibernate.hbm2dll.create_namespaces

#к выбору в качестве активной - default_schema
# и для гарантии datasource.url (currentSchema)

spring:
  application:
    name: bks_crm
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bks
    username: postgres
    password: andreymstepanov
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    #как пишет Baeldung, If we still want to have both Hibernate automatic schema generation in conjugation with script-based schema creation and data population, we'll have to use: true
    #This will ensure, that after Hibernate schema creation is performed then additionally schema.sql is read for any additional schema changes and data.sql is executed to populate the database.
    # на самом деле, если это свойство false,  схема и таблицы не будут созданы вовсе, если data.sql есть на classpath. Если нет файла, схема и таблицы созданы будут
    #схема  - spring.datasource.url (...?currentSchema); таблицы - по сущностям
    defer-datasource-initialization: true
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: create
      hibernate:
        ddl-auto: update
        hbm2dll:
          create_namespaces: true
        show_sql: false
        format_sql: true
        connection:
          autocommit: false
        default_schema: bks
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp:
          use_jdbc_metadata_defaults: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#  liquibase:
#    enabled: true
#    default_schema: bks
#    change-log: classpath:/db/changelog/db.changelog-master.yml
#    database-change-log-lock-table: bks_databasechangeloglock
#    database-change-log-table: bks_databasechangelog

  #script-based initialization is performed by default only for embedded databases
  #to always initialize a database using scripts - schema.sql and data.sql USE spring.sql.init.mode=always
  sql:
    init:
      mode: always

logging:
  file:
    name: logs/bks.log

scheduler:
  interval: 30000

app:
  client_exchange: clientExchange
  client_queue: clientQueue